[package]
name = "osmo-bindings"
version = "0.7.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Osmosis blockchain"
repository = "https://github.com/confio/osmosis-bindings"
homepage = "https://osmosis.zone"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std = "1.1"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
